version: '3'
services:
  traefik:
#    image: traefik:v2.11
    image: traefik:v2.4
    command: 
      - "--api.insecure=true" 
      - "--providers.docker=true"
      - "--providers.docker.swarmmode" 
#      - "--entrypoints.web.address=:80" 
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=voting_test"
#      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    ports:
      - "80:80"
      - "5601:5601"
      - "8080:8080"
    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock


    networks:
      - voting_test
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.84.201.156.116.nip.io`)"
        - "traefik.http.middlewares.auth.basicauth.users=rebrainme:$$2y$$05$$RNCeK1L0FTxriHSeRIByo.O1XEvRZYkE3H.FDwGhQ/NqgOb4pmtwe"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.services.kibana.loadbalancer.server.port=8080"

#  whoami:
#    image: traefik/whoami
#   networks:
#      - voting_test
#    deploy:
#      replicas: 2
#      labels:
#        - "traefik.http.routers.whoami.rule=Host(`whoami.178.154.200.5.nip.io`)"
#      проверить здесь
#        - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
#        - "traefik.http.services.my-container-service.loadbalancer.server.port=80"

networks:
  voting_test:
    external: true
